name: Build

on:
  push:
    branches: [main, alpha, beta, "jam/*", "build/*"]
  release:
    types: [created]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build:Web
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Inject Variables
      uses: rlespinasse/github-slug-action@v2.x
    - name: Setup Node Environment
      uses: actions/setup-node@v1
      with:
        node-version: "14.x"
    - name: Install Dependencies
      run: npm ci
    - name: Build Artifact
      run: npm run build
      env:
        FORCE_COLOR: true
    - name: Deploy Artifact
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        clean: true
        branch: gh-pages
        folder: builds/web
        target-folder: ${{ env.GITHUB_REF_SLUG }}
        commit-message: Deploying ${{ github.sha }} to ${{ env.GITHUB_REF_SLUG }}
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
